[package]
name = "rust-skse-plugin"
version = "0.1.0"
authors = ["Tyler Hallada <tyler@hallada.net>"]
edition = "2018"

[dependencies]
log = "0.4"
simple-logging = "2.0"
dirs = "3.0"

[lib]
name = "RustSKSEPlugin"
crate-type = ["cdylib"]